export const listCameraFake = [
  {
    id: 889,
    name: 'IPCamera 0229',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 0229',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 888,
    name: 'IPCamera 02282',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 02228',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 887,
    name: 'IPCamera 0227',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 0227',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 886,
    name: 'IPCamera 0226',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 0226',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 885,
    name: 'IPCamera 0225',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 0225',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 884,
    name: 'IPCamera 02224',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 02224',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 883,
    name: 'IPCamera 02223',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 02223',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 882,
    name: 'IPCamera 02221',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 02221',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 881,
    name: 'IPCamera 0222',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 0222',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 880,
    name: 'IPCamera 021',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 021',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 858,
    name: 'IPCamera 02',
    type: 'CAMERA',
    information: {
      name: 'IPCamera 02',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.124.77',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 2,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 2,
      enableAnr: false,
      _version: '1.0',
      channelId: '',
      streamingProxyChannelIdList: [],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'OFFLINE',
  },
  {
    id: 857,
    name: 'Camera 01',
    type: 'CAMERA',
    information: {
      name: 'Camera 01',
      sourceInputPortDescriptor: {
        deviceID: null,
        userName: 'admin',
        ipAddress: '10.150.122.69',
        streamType: 'auto',
        managePortNo: 8000,
        srcInputPort: 1,
        proxyProtocol: 'HIKVISION',
        addressingFormatType: 'ipaddress',
      },
      id: 1,
      enableAnr: false,
      _version: '1.0',
      channelId: 101,
      streamingProxyChannelIdList: [101, 102],
    },
    config: null,
    status: 'ACTIVE',
    area: {
      areaId: 19,
      areaCode: 'Z100/000',
      areaName: 'Ocean Park',
      longitude: null,
      latitude: null,
      pint: '8224',
    },
    zone: {
      zoneId: 1,
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      parentId: null,
      areaId: 19,
      parentName: null,
    },
    block: {
      blockId: 1,
      zoneId: 1,
      areaId: 19,
      areaName: 'Ocean Park',
      blockCode: 'S1.01',
      blockName: 'S1.01',
      zoneCode: 'S1',
      zoneName: 'Sapphire 1',
      longitude: null,
      latitude: null,
    },
    floor: null,
    unit: null,
    area_id: 19,
    zone_id: 1,
    block_id: 1,
    floor_id: 0,
    parent: {
      id: 856,
      name: 'NVR Mr HIEN 123',
      type: 'NVR',
      information: {
        deviceType: 'NVR',
        serialNumber: 'DS-7616NI-K1(B)1620200911CCRRE81022343WCVU',
        firmwareReleasedDate: 'build 200715',
        ip: '10.150.122.68',
        deviceID: '48453831-3032-3233-3433-c0517e265218',
        deviceName: 'NVR Mr HIEN 123',
        encoderVersion: 'V5.0',
        password: 'jqFIbtsPkMJLaI/2yKbpMA==',
        macAddress: 'c0:51:7e:26:52:18',
        telecontrolID: 255,
        port: '80',
        _encoding: 'UTF-8',
        _xmlns: 'http://www.hikvision.com/ver20/XMLSchema',
        model: 'DS-7616NI-K1(B)',
        encoderReleasedDate: 'build 200706',
        firmwareVersion: 'V4.30.010',
        _version: '1.0',
        username: 'admin',
      },
      config: null,
      status: 'ACTIVE',
      area: null,
      zone: null,
      block: null,
      floor: null,
      unit: null,
      area_id: 19,
      zone_id: 0,
      block_id: 0,
      floor_id: 0,
      parent: null,
      number_of_children: null,
      status_of_device: null,
    },
    number_of_children: 0,
    status_of_device: 'ONLINE',
  },
];
