export const LOAD_DATA = 'app/ROOM_DEVICE/LOAD_DATA';
export const LOAD_DATA_SUCCESS = 'app/ROOM_DEVICE/LOAD_DATA_SUCCESS';
export const LOAD_DATA_ERROR = 'app/ROOM_DEVICE/LOAD_DATA_ERROR';
export const SHOW_LOADING = 'app/ROOM_DEVICE/SHOW_LOADING';
export const LOAD_DETAIL = 'app/ROOM_DEVICE/LOAD_DETAIL';
